# Generated by Django 4.1.3 on 2022-11-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("isdeleted", models.BooleanField(db_column="isDeleted")),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                ("comment", models.TextField()),
                ("username", models.CharField(max_length=1)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "comment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("isdeleted", models.BooleanField(db_column="isDeleted")),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                ("name", models.CharField(max_length=1)),
                ("image", models.TextField()),
                ("url", models.TextField()),
                ("language", models.CharField(max_length=1)),
                ("summary", models.TextField()),
            ],
            options={
                "db_table": "movie",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("isdeleted", models.BooleanField(db_column="isDeleted")),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                ("average", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "rating",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("isdeleted", models.BooleanField(db_column="isDeleted")),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                ("type", models.TextField()),
            ],
            options={
                "db_table": "reaction",
                "managed": False,
            },
        ),
    ]
